name: Generate Svg

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Svg
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
      
      # Snake Animation
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
        # github user name to read the contribution graph from (**required**)
        # using action context var `github.repository_owner` or specified user
          github_user_name: YanDao0313

          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          #  supported options:
          #  - palette:     A preset of color, one of [github, github-dark, github-light]
          #  - color_snake: Color of the snake
          #  - color_dots:  Coma separated list of dots color.
          #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                 Exactly 5 colors are expected.
          outputs: |
            static/github-snake.svg
            static/github-snake-dark.svg?palette=github-dark
            static/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
      # Commit json into repo
      - name: Commit
        env:
          $USER_EMAIL: ${{ secrets.USER_EMAIL }}
          $USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          git add .
          git commit -m "generate `SVG` files and push successfully" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
